# Generated by Django 2.2a1 on 2019-01-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo_img', models.ImageField(upload_to='')),
                ('Photo_name', models.CharField(max_length=200)),
                ('Photo_about', models.TextField()),
                ('Photo_date', models.DateTimeField(auto_now_add=True)),
                ('Photo_likes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
        migrations.CreateModel(
            name='UserAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=200)),
                ('User_age', models.IntegerField()),
            ],
            options={
                'db_table': 'UserAcc',
            },
        ),
        migrations.CreateModel(
            name='CommentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_text', models.TextField(verbose_name='Комментарий')),
                ('Comment_date', models.DateTimeField(auto_now_add=True)),
                ('Comment_likes', models.IntegerField(default=0)),
                ('Comment_Photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Photo')),
                ('Comment_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CommentPhoto',
            },
        ),
    ]
