# Generated by Django 2.1.5 on 2019-01-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190131_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Photo_img',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
